services:
    db:
        image: leadsdoit/postgres-16:1.0
        container_name: ${NAME_SERVICE:-tplfastapi}_db_pgsql
        restart: always
        volumes:
            - ".db/data:/var/lib/postgresql/data"
            - ".db/dump:/backup"
        ports:
            - "11100:5432"
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}